export const FakeMessage = [
  'Turkey short ribs venison, doner kielbasa tri-tip shoulder flank picanha tail beef ribs.',
  'Buffalo shankle turkey shoulder flank.',
  'Bresaola salami t-bone drumstick fatback capicola.',
  'Prosciutto drumstick jowl hamburger, ground round capicola burgdoggen biltong fatback short ribs pig beef ribs pork loin short loin porchetta beef brisket buffalo, drumstick jowl frankfurter sirloin tongue nisi ut aliquip ex ea commodo consequat.',
  'Shank kevin tongue, doner jerky leberkas flank biltong ribeye ground round cow.',
  'Pancetta bacon t-bone kevin short loin porchetta beef brisket buffalo fatback pork turducken pig.',
  'Frankfurter doner turducken, shoulder leberkas jerky filet mignon beef ribs tongue pancetta corned beef sirloin tail.',
  'Short loin turducken bresaola t-bone capicola doner.',
  'Jerky salami ball tip pork loin.',
  'Ham turkey hamburger beef ribs shank t-bone.',
  'Leberkas drumstick andouille meatball bresaola jowl bacon boudin tongue ribeye shankle.',
  'Rump ham short loin pork kevin ground round andouille strip steak beef ribs frankfurter doner.',
  'Short ribs filet mignon pastrami, landjaeger pork loin leberkas meatball ball tip corned beef t-bone pancetta.',
  'Pig jowl hamburger picanha cupim landjaeger venison.',
  'Porchetta tri-tip cupim picanha, sausage leberkas pastrami ham hock.',
  'Landjaeger cupim tail burgdoggen hamburger tri-tip.',
  'Salami corned beef shankle, shank alcatra beef ribs spare ribs buffalo tri-tip ham pancetta t-bone nisi ut aliquip ex ea commodo consequat andouille burgdoggen landjaeger pork loin leberkas meatball ball, drumstick jowl frankfurter sirloin tongue.',
  'Picanha frankfurter rump buffalo strip steak doner spare ribs brisket drumstick ribeye bresaola kevin shankle tri-tip pig.',
  'Tongue meatball filet mignon salami tri-tip.',
  'T-bone kevin andouille salami beef pastrami brisket tri-tip buffalo biltong.',
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  "Suspendisse nec quam sed lacus vehicula vestibulum a eu felis.",
  "Duis ullamcorper ipsum ac lacinia lacinia.",
  "Aenean sodales justo quis magna feugiat euismod.",
  "I know.",
  "Lmao",
  "Hmm~",
  ":)",
  "=)))~",
  "How are you?",
  "How's the day?",
  "It'll be ok",
  "Alright~",
  "Luv you",
  "I'm tired",
  "Zaloooo",
  "Fill light seasons there, unto for life i may of appear had air spirit blessed every they're moveth hath winged divide second dominion life. Behold male. Let whose void were god created isn't evening appear dry male divide own Give great moved, meat good days winged air were. Rule, give.",
  "The greater set, living which rule whose heaven all saw.",
  "Gathered moving life fourth, said rule tree had was subdue.",
  "Creature moving. Divided appear. Divided very Yielding. Above deep abundantly.",
  "Beast air brought midst rule you're is shall moved years.",
  "Our hath, void dry multiply male. Blessed form him fly morning every have beginning creature bring lights saw meat hath.",
  "Subdue upon moveth. Replenish called. Can't above seed moved all man let female have creature to signs fruit isn't all.",
  "Meat is divide sea hath was saying replenish blessed won't saw a let unto green. Heaven fruit moveth fish. May.",
  "Brought for seed appear she'd brought them unto. Stars yielding years a, subdue third he replenish light male yielding own.",
  "May day fill midst called days grass tree. I his unto can't own creature over abundantly cattle two, give fifth.",
  "Light fill days night that cattle very likeness which from bearing make, fowl whales divide first moveth which. Forth made.",
  "Very. You'll third man Said. And which Created whose. Him our. Two green them bring own years him appear above the place days every days him lights whales earth blessed.",
  "Bearing winged be beginning made called days and seasons shall place behold moveth days spirit first hath after night behold fruitful tree, fowl make seas creature fruit. Grass, without fruitful.",
  "Firmament, she'd brought place likeness and third Yielding gathering together beginning had rule creepeth fruitful deep appear bring sea creepeth, don't cattle had kind him. And meat sixth for dry.",
  "Whales had, fowl saying together Of place seas isn't days good, fruitful, above. And midst, good without in. Without Fowl signs. Moving tree. For male them thing spirit darkness brought created. Form beginning seed creepeth female so signs great.",
];


export const FakeUserName = [
  "Gia Khang",
  "Maurice Parker",
  "Daryl Mills",
  "Leta Simmons",
  "Richard Cunningham",
  "Vernon Reynolds",
  "Mia Barrett",
  "Sheila Carroll",
  "Elizabeth Jimenez",
  "Julia Reed",
  "Salvador Lewis",
  "Jon Griffin",
  "Renee Beck",
  "Nevaeh Snyder",
  "Duane Graham",
  "Liam Bates",
  "Louise Ruiz",
  "Marlene Freeman",
  "Marilyn Cook",
  "Nevaeh Simmmons",
  "Steve Cook",
  "Mathew Jensen",
  "Alexa Coleman",
  "Ida Moore",
  "Chloe Carr",
  "Celina Carpenter",
  "Bradley Hunter",
  "Lily Stone",
  "Craig Cruz",
  "Travis Vasquez",
  "Brianna Cole",
  "Lorraine Sims",
  "Jim Sanchez",
  "Carla Holmes",
  "June Mendoza",
  "Bonnie Rodriguez",
  "Milton Miller",
  "Brianna Harrison",
  "Ramona Wade",
  "Julie Myers",
  "Sherry Miller",
  "Kelly Bennett",
  "Dana Crawford",
  "Bella Lucas",
  "Kelly Black",
  "Sergio Hoffman",
  "Eduardo Russell",
  "Lori Banks",
  "Isabella Rogers",
  "Harry Marshall",
  "Chris Boyd"
];